
# Application name
TARGET=MyProgram

# Where to find user C code
USR_PATH=.

# -----------
# user C code
# -----------
USR_CFILES=\
   kernel_cfg.c\
   Fonctionnement.c\
   Comportement.c \
   glue.c\

include $(MDL2LUS2OSEK)/generic.mak
